language: ruby
rvm:
  - 2.4.6
  - 2.5.3

services:
  - postgresql

before_install:
  # Install a current Bundler version
  - gem install bundler -v '< 2'

before_script:
  # Setup Test Database
  - psql -c 'create database helpy_test;' -U postgres
  # Prepare 'jshint' executable for JavaScript linting
  - npm install -g jshint

script:
  # Load database schema
  - bundle exec rake db:schema:load
  # Test suite
  - bundle exec rake
  # Brakeman security scanner
  - bundle exec brakeman -z
  # Check vulnerable gems
  - bundle exec bundle-audit check --update --ignore CVE-2015-9284 CVE-2019-16676
  # Rubocop static code analyzer
  - bundle exec rubocop
  # SCSS analyzer
  - bundle exec scss-lint
  # JavaScript analyzer
  - jshint ./app

cache: bundler

addons:
    code_climate:
        repo_token: 8aed69acf532241f5281042dc5b1a5d89ea9206773d079ce2de838a28f0f5041
    chrome: stable
    apt:
      packages:
        - chromium-chromedriver
