apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: helpy
  name: helpy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: helpy
    spec:
      imagePullSecrets:
      - name: dockercred
      containers:
      - env:
        - name: POSTGRES_DB
          value: helpy_production
        - name: POSTGRES_PASSWORD
          value: some_secure_pg_password_change_in_production
        - name: POSTGRES_USER
          value: helpy
        - name: SECRET_KEY_BASE
          value: some_secret_key_base_change_in_production
        image: superpedestrian/helpy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: helpy-http
          protocol: TCP
        name: helpy
        resources: {}
        volumeMounts:
        - mountPath: /helpy/public
          name: helpy-rails-assets
      restartPolicy: Always
      volumes:
      - name: helpy-rails-assets
        persistentVolumeClaim:
          claimName: helpy-rails-assets
status: {}
