apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-helpy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-helpy
    spec:
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.25.0" 
        command: 
        - "rm"
        - "-fr"
        - "/var/lib/postgres/lost+found"
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgres
      containers:
        - name: postgres-helpy
          image: postgres:9.6.2
          envFrom:
          - configMapRef:
              name: {{ .Values.service.configMapName }}
          ports:
            - name: postgres-helpy
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data/pgdata   
      subPath: postgresql-db
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-claim0
